package cmd

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"runtime"

	"github.com/spf13/cobra"
)

var sentinelCmd = &cobra.Command{
	Use:   "sentinel",
	Short: "Manage Sentinel pre-commit hooks",
}

var sentinelInstallCmd = &cobra.Command{
	Use:   "install",
	Short: "Install pre-commit hooks in the current git repository",
	RunE:  runSentinelInstall,
}

var sentinelCheckCmd = &cobra.Command{
	Use:   "check",
	Short: "Run sentinel validation on staged files (without committing)",
	RunE:  runSentinelCheck,
}

var sentinelRunCmd = &cobra.Command{
	Use:    "run",
	Short:  "Run sentinel validation (called by git hook)",
	Hidden: true,
	RunE:   runSentinelRun,
}

var sentinelHookType string

func init() {
	sentinelCmd.AddCommand(sentinelInstallCmd)
	sentinelCmd.AddCommand(sentinelCheckCmd)
	sentinelCmd.AddCommand(sentinelRunCmd)
	sentinelRunCmd.Flags().StringVar(&sentinelHookType, "hook", "pre-commit", "Hook type: pre-commit | pre-push")
}

func runSentinelInstall(cmd *cobra.Command, args []string) error {
	gitDir, err := findGitDir()
	if err != nil {
		return fmt.Errorf("not in a git repository: %w", err)
	}

	hooksDir := filepath.Join(gitDir, "hooks")
	if err := os.MkdirAll(hooksDir, 0755); err != nil {
		return fmt.Errorf("creating hooks directory: %w", err)
	}

	korvaPath, err := resolveKorvaBinary()
	if err != nil {
		return fmt.Errorf("cannot find korva binary: %w", err)
	}

	// Install pre-commit hook
	hookPath := filepath.Join(hooksDir, "pre-commit")
	content := buildHookContent(korvaPath, "pre-commit")
	if err := os.WriteFile(hookPath, []byte(content), 0755); err != nil {
		return fmt.Errorf("writing pre-commit hook: %w", err)
	}

	printSuccess(fmt.Sprintf("Installed pre-commit hook at %s", hookPath))
	printInfo("The hook calls 'korva sentinel run --hook=pre-commit' on every commit")
	return nil
}

func runSentinelCheck(cmd *cobra.Command, args []string) error {
	return runSentinelValidation("pre-commit")
}

func runSentinelRun(cmd *cobra.Command, args []string) error {
	return runSentinelValidation(sentinelHookType)
}

func runSentinelValidation(hookType string) error {
	// Get staged files
	out, err := exec.Command("git", "diff", "--cached", "--name-only", "--diff-filter=ACM").Output()
	if err != nil {
		//nolint:nilerr // intentional: failed git diff means no staged files, let commit proceed
		return nil
	}

	if len(out) == 0 {
		return nil
	}

	fmt.Printf("Sentinel: validating staged files...\n")

	// For now, run basic checks directly in Go
	// The full Go validator (korva-sentinel) handles advanced AST analysis
	violations := basicChecks(string(out))

	if len(violations) > 0 {
		fmt.Println("\nSentinel found violations:")
		for _, v := range violations {
			fmt.Printf("  ✗ %s\n", v)
		}
		fmt.Println("\nFix violations before committing, or use // korva-ignore: <reason>")
		return fmt.Errorf("sentinel: %d violation(s) found", len(violations))
	}

	fmt.Println("Sentinel: all checks passed")
	return nil
}

// basicChecks runs lightweight pattern-based checks on staged content.
func basicChecks(stagedFiles string) []string {
	var violations []string

	out, err := exec.Command("git", "diff", "--cached", "--unified=0").Output()
	if err != nil {
		return nil
	}

	content := string(out)

	// Check for console.log in TypeScript/JavaScript source files
	if containsPattern(content, `+.*console\.log`) && containsSuffix(stagedFiles, ".ts", ".js", ".tsx") {
		violations = append(violations, "console.log detected in source files — use the team logger instead")
	}

	// Check for 'any' type without korva-ignore comment
	if containsPattern(content, `+.*: any`) && !containsPattern(content, `korva-ignore`) && containsSuffix(stagedFiles, ".ts") {
		violations = append(violations, "TypeScript 'any' type detected — add '// korva-ignore: <reason>' if intentional")
	}

	return violations
}

func buildHookContent(korvaPath, hookType string) string {
	if runtime.GOOS == "windows" {
		// git-bash compatible script for Windows
		return fmt.Sprintf("#!/bin/sh\n# Generated by korva sentinel install\nexec %q sentinel run --hook=%s\n",
			filepath.ToSlash(korvaPath), hookType)
	}
	return fmt.Sprintf("#!/bin/sh\n# Generated by korva sentinel install\nexec %q sentinel run --hook=%s\n",
		korvaPath, hookType)
}

func findGitDir() (string, error) {
	out, err := exec.Command("git", "rev-parse", "--git-dir").Output()
	if err != nil {
		return "", fmt.Errorf("not a git repository")
	}
	gitDir := filepath.Clean(string(out[:len(out)-1])) // trim newline
	return gitDir, nil
}

func resolveKorvaBinary() (string, error) {
	// Try PATH first
	if path, err := exec.LookPath("korva"); err == nil {
		return path, nil
	}
	// Try same directory as current executable
	self, err := os.Executable()
	if err != nil {
		return "", fmt.Errorf("cannot determine executable path")
	}
	candidate := filepath.Join(filepath.Dir(self), "korva")
	if runtime.GOOS == "windows" {
		candidate += ".exe"
	}
	if _, err := os.Stat(candidate); err == nil {
		return candidate, nil
	}
	return "", fmt.Errorf("korva binary not found in PATH or alongside current executable")
}

func containsPattern(content, pattern string) bool {
	// Simple substring check (not regex)
	for _, line := range splitLines(content) {
		if len(line) > 0 && len(pattern) > 0 {
			if fuzzyContains(line, pattern) {
				return true
			}
		}
	}
	return false
}

func containsSuffix(files string, suffixes ...string) bool {
	for _, suffix := range suffixes {
		for _, f := range splitLines(files) {
			if len(f) >= len(suffix) && f[len(f)-len(suffix):] == suffix {
				return true
			}
		}
	}
	return false
}

func fuzzyContains(s, sub string) bool {
	if len(sub) > len(s) {
		return false
	}
	for i := 0; i <= len(s)-len(sub); i++ {
		if s[i:i+len(sub)] == sub {
			return true
		}
	}
	return false
}

func splitLines(s string) []string {
	var lines []string
	start := 0
	for i := 0; i < len(s); i++ {
		if s[i] == '\n' {
			lines = append(lines, s[start:i])
			start = i + 1
		}
	}
	if start < len(s) {
		lines = append(lines, s[start:])
	}
	return lines
}
